[package]
name = "esp_buddy_rs"
version = "0.1.0"
authors = ["Juraj Michálek <juraj.michalek@espressif.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
embedded-graphics = "0.7"
embedded-hal = "0.2"
esp-alloc = { version = "0.1.0", features = ["oom-handler"] }
# esp32-hal = { package = "esp32-hal", git = "https://github.com/esp-rs/esp-hal.git", rev = "e9f22ac", features = [ "smartled" ]}
esp32-hal = { package = "esp32-hal", version = "0.5", features = [ "smartled" ]}
esp-backtrace = { version = "0.1.0", features = ["esp32", "panic-handler", "print-uart"] }
ssd1306 = "0.7.1"

xtensa-lx-rt = { version = "0.13.0", features = ["esp32"], optional = true }

# Blinky dependency
# ws2812-esp32-rmt-driver = "0.4.0"
smart-leds        = "0.3.0"
hts221 = "0.3.0"
esp-println = { version = "0.2.1", features = [ "esp32" ] }
esp-wifi = { git = "https://github.com/esp-rs/esp-wifi.git", features = [ "esp32", "wifi", "embedded-svc" ]}
embedded-svc = { version = "0.22.1", default-features = false, features = [], optional = true }
shared-bus = "0.2.4"
heapless = "0.7.16"

[features]
default = ["rt"]
rt = ["xtensa-lx-rt"]
